CREATE DATABASE JuicyNews

GO

USE JuicyNews

CREATE TABLE Users
(
	UserId INT PRIMARY KEY IDENTITY(1, 1),
	Username NVARCHAR(30) NOT NULL,
	Password NVARCHAR(30) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	FirstName NVARCHAR(20) NOT NULL,
	LastName NVARCHAR(20) NOT NULL,
	RegistrationDate DATE NULL
)

CREATE TABLE News
(
	NewsId INT PRIMARY KEY IDENTITY(1, 1),
	Title NVARCHAR(150) NOT NULL,
	Content NVARCHAR(MAX) NOT NULL,
	UserId INT FOREIGN KEY REFERENCES Users NOT NULL,
	DateOfPublishing DATE NOT NULL,
	DateOfLastEdit DATE NULL
)

CREATE TABLE Comments
(
	CommentId INT PRIMARY KEY IDENTITY(1, 1),
	NewsId INT FOREIGN KEY REFERENCES News NOT NULL,
	UserId INT FOREIGN KEY REFERENCES Users NOT NULL,
	Content NVARCHAR(500) NOT NULL
)